[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version = "0.9.3"
edition = "2018"

[[bin]]
name = "plato"
path = "src/main.rs"

[[bin]]
name = "plato-import"
path = "src/importer.rs"
required-features = ["importer"]

[[bin]]
name = "plato-emulator"
path = "src/emulator.rs"
required-features = ["emulator"]

[[bin]]
name = "article_fetcher"
path = "src/fetcher.rs"
required-features = ["fetcher"]

[dependencies]
bitflags = "1.2.1"
downcast-rs = "1.2.0"
lazy_static = "1.4.0"
libc = "0.2.76"
png = "0.16.7"
regex = "1.3.9"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
titlecase = "1.1.0"
unicode-normalization = "0.1.13"
toml = "0.5.6"
zip = "0.5.8"
kl-hyphenate = "0.7.3"
entities = "1.0.1"
paragraph-breaker = "0.4.3"
xi-unicode = "0.2.1"
septem = "1.0.1"
byteorder = "1.3.4"
flate2 = "1.0.14"
levenshtein = "1.0.4"
nix = "0.18.0"
indexmap = { version = "1.6.0", features = ["serde-1"] }
anyhow = "1.0.32"
thiserror = "1.0.20"
walkdir = "2.3.1"
globset = "0.4.5"
filetime = "0.2.12"
fxhash = "0.2.1"
rand_core = "0.5.1"
rand_xoshiro = "0.4.0"

[dependencies.getopts]
version = "0.2.21"
optional = true

[dependencies.reqwest]
version = "0.10.8"
features = ["rustls-tls", "json", "blocking"]
default-features = false
optional = true

[dependencies.chrono]
features = ["serde"]
version = "0.4.15"

[dependencies.sdl2]
version = "0.34.3"
optional = true

[dependencies.crossbeam-channel]
version = "0.4.4"
optional = true

[dependencies.signal-hook]
version = "0.1.16"
optional = true

[features]
importer = ["getopts"]
emulator = ["sdl2"]
fetcher = ["reqwest", "crossbeam-channel", "signal-hook"]
